### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by AlexKutschera** [Cretezy/braintree-web-drop-in-react#1]
Uncaught (in promise) DropinError {name: "DropinError", message: "options.authorization is required.", _braintreeWebError: undefined}

Authorization was provided like in the example

**Comment by Cretezy** [comment]
Ah, yes, there's a mistake in the example. Pass `authorization` in the options directly. I'll update the docs in a minute.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/braintree-web-drop-in-react/commit/921f6e0bff693672809e1b165f69240f27e73a70
