### ISSUE TITLE
set preselectVaultedPaymentMethod to false

### ISSUE THREAD

**Issue by andylaci** [Cretezy/braintree-web-drop-in-react#10]
hello, how to achieve this? Didn't find it anywhere in docs my code looks like this:

```
        <DropIn
          options={{
            authorization: clientToken,
            threeDSecure: {
              amount: '1.00',
            },
          }}
          onInstance={instance => (this.instance = instance)}
          onPaymentOptionSelected={this.addCard.bind(this)}
        />
```

my goal is to switch between already filled in cards, found `preselectVaultedPaymentMethod ` must be set to false, I might be wrong

**Comment by Cretezy** [comment]
I believe you have to place it in `options`.

Let me know if that works!
