### ISSUE TITLE
Check to see if the "Choose Another Way To Pay" button has been clicked

### ISSUE THREAD

**Issue by rrozema12** [Cretezy/braintree-web-drop-in-react#13]
I am conditionally rendering buttons with specific actions and, and would like to know if there is a boolean value to see if that has been clicked.

**Comment by Cretezy** [comment]
You could use the `paymentOptionSelected` event. 

Use `ref.instance.on("paymentOptionSelected", callback)` to listen, `ref` being what you save this component reference as (would be `this.instance.instance.on...` if using the example).
