### ISSUE TITLE
Can't resolve '@babel/runtime/core-js/object/get-prototype-of'

### ISSUE THREAD

**Issue by KaiserPhemi** [Cretezy/braintree-web-drop-in-react#14]
# General Information
- Package Version: `1.0.4`
- Environment: Node

# Issue
I keep getting the error message `Can't resolve '@babel/runtime/core-js/object/get-prototype-of'` when I tried to run my app.
After some debugging, I realized the module `get-prototype-of` is within another package `@babel/runtime-corejs2`. 

# Partial Fix
- Install `@babel/runtime` and `@babel/plugin-transform-runtime` as `devDependencies`
- Modify `@babel/runtime/core-js/object/get-prototype-of` within `index.js` to point to the appropriate folder in `@babel/runtime-corejs2/`

# Issue
I was able to run my app but every time I update/add/remove any npm package, I lose all modification to `index.js` within the package folder.
Is there a better way to permanently fix this?

**Comment by jchappell82** [comment]
Hi @Cretezy  - I noticed you pushed an updated release to GitHub, but it isn't currently published to npm.  Was that intended?

**Comment by Cretezy** [comment]
The deploy build step failed but didn't actually error: https://travis-ci.org/Cretezy/braintree-web-drop-in-react/jobs/415447378#L506

I've just published the update manually :champagne:

**Comment by jchappell82** [comment]
Thank you!
