### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Manviel** [Cretezy/braintree-web-drop-in-react#170]
When i using this package with typescript i need to install types. When i write:
npm install @types/braintree-web-drop-in-react
I get the error 404.
Please, add file .d.ts

**Comment by Cretezy** [comment]
TypeScript typings have been there since v1.1.0:
https://github.com/Cretezy/braintree-web-drop-in-react/blob/master/index.d.ts

No need to add any separate package.
