### ISSUE TITLE
Syntax to Obtain Device Data?

### ISSUE THREAD

**Issue by VikR0001** [Cretezy/braintree-web-drop-in-react#196]
What's the correct syntax to use with this package in order to obtain device data to send to the server?

I've looked at the [Braintree docs recommending that we obtain device data](https://developers.braintreepayments.com/guides/advanced-fraud-tools/device-data-collection/javascript/v3). I'm trying this:

```
<DropIn
	options={{
		authorization: this.state.clientToken,
		paypal: {
			flow: 'vault'
		},
		dataCollector:{
			kount: true,
			paypal: true
		}
	}}
	onInstance={(instance) => (this.instance = instance)}
/>
```

...but I haven't yet found a way to observe the device data after the component loads. 

What is the correct syntax to use to obtain the device data?

**Comment by Cretezy** [comment]
Use the `instance` in the `onInstance` to create it as per the docs:

```js
onInstance{instance => {
  braintree.dataCollector.create({
    client: instance,
    paypal: true
  }, function (err, dataCollectorInstance) {
    if (err) {
      // Handle error in creation of data collector
      return;
    }
    // At this point, you should access the dataCollectorInstance.deviceData value and provide it
    // to your server, e.g. by injecting it into your form as a hidden input.
    var deviceData = dataCollectorInstance.deviceData;
  });
}}
```

**Comment by VikR0001** [comment]
Thanks for this great info! Is there an instance of `braintree` already loaded by `braintree-web-drop-in-react` I can access inside `onInstance`?  Alternatively, what is the best npm package to import in order to have access to an instance of `braintree`?

**Comment by Cretezy** [comment]
`braintree` is the imported package, see docs that you linked :smiley:

**Comment by VikR0001** [comment]
I've got this:

```
import braintree from "braintree-web";

[.....]

<DropIn
	options={{
		authorization: this.state.clientToken,
		paypal: {
			flow: 'vault'
		},
	}}
	onInstance={(instance) => {
		braintree.dataCollector.create({
			client: instance,
			paypal: true
		}, function (err, dataCollectorInstance) {
			if (err) {
				return;
			}
			var deviceData = dataCollectorInstance.deviceData;
			debugger;
		});
	}
	}
/>
```

In the browser, on the call to `braintree.dataCollector.create`, I'm getting:

> TypeError: client.getVersion is not a function

What am I leaving out?

**Comment by Cretezy** [comment]
Ah my bad. `dataCollector` is on `instance` as seen from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree-web-drop-in/index.d.ts#L30

Hopefully that helps!

**Comment by brideo** [comment]
I'm not sure if this is the cleanest way but I ended up doing this if it helps anybody else 

`
    getDeviceData() {
        const braintree = require('braintree-web/client')
        const braintreeDataCollector = require('braintree-web/data-collector')

        return braintree.create({
            authorization: this.props.clientToken
        }).then(clientInstance => {
            return braintreeDataCollector.create({
                client: clientInstance,
                kount: true
            });
        }).then(function (dataCollectorInstance) {
            return dataCollectorInstance.deviceData;
        })
    }

        this.getDeviceData().then(deviceData => {
            this.setState({deviceData: deviceData})
        })
`
