### ISSUE TITLE
Feature Request: Function-Based Version?

### ISSUE THREAD

**Issue by VikR0001** [Cretezy/braintree-web-drop-in-react#197]
Using `braintree-web-drop-in-react` has been a big win for me! It's working great.

Would you potentially consider doing a function-based version at some point in the future?

**Comment by Cretezy** [comment]
Can you explain what is a "function-based version"? Not sure what you mean

**Comment by VikR0001** [comment]
Surely. React components were previously class-based, but the latest React code prefers function-based components, which support hooks and soon, concurrent React as well. You probably know more about this than I do but just call it by some other terminology. Here's a relevant link: https://reactjs.org/docs/hooks-state.html#hooks-and-function-components

**Comment by Cretezy** [comment]
No reason to change working code inside the library.

For the usage, you can definitely use this inside functions with no issues, since it's just a component.

I would rewrite it as a functional component if I ever rewrite it, but this code is stable and isn't a maintenance burden

**Comment by VikR0001** [comment]
Very good. Thanks for the info!
