### ISSUE TITLE
Getting this error while starting example 

### ISSUE THREAD

**Issue by mallikarjunece** [Cretezy/braintree-web-drop-in-react#20]
λ yarn start                                                                                                                                          
yarn run v1.12.3                                                                                                                                      
warning package.json: No license field                                                                                                                
$ parcel index.html                                                                                                                                   
Server running at http://localhost:1234                                                                                                               
braintree-web-drop-in-react\example\index.js: Cannot resolve dependency '.\dist' at braintree-web-drop-in-react\example\dist'                                                                                                         
    at braintree-web-drop-in-react\example\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17      
    at process (braintree-web-drop-in-react\example\node_modules\browser-resolve\node_modules\resolve\lib\async.js:17
3:43)                                                                                                                                                 
×  loadedAssets is not iterable                                                                                                                       
    at Bundler.bundle (braintree-web-drop-in-react\example\node_modules\parcel-bundler\src\Bundler.js:179:61)        
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Cretezy** [comment]
Do `yarn build` in the root directory because running the example. You're missing the output directory (`dist`) which gets created when `yarn build` is ran

**Comment by shan-du** [comment]
I'm still getting this same error running npm, followed exact instruction in README.
```
cd example
npm i
npm start
```

node version: 8.9.4
npm version: 5.6.4
macOS 10.12.6
