### ISSUE TITLE
onPaymentMethodRequestable not working with credit cards

### ISSUE THREAD

**Issue by ProductOfAmerica** [Cretezy/braintree-web-drop-in-react#21]
The gif should show the issue. Basically, even when I enter valid info into the pane, ```paymentMethodIsSelected``` is `false` even after all the correct fields are filled in.

![2018-11-22_15-22-02](https://user-images.githubusercontent.com/14712114/48922202-b119c400-ee6a-11e8-8c33-9633d1d1ba33.gif)

**Comment by Cretezy** [comment]
This seems to be an issue with `braintree-web-drop-in`, not this library. Please open an issue there

**Comment by ProductOfAmerica** [comment]
Ok, thanks!
