### ISSUE TITLE
Feature Request: Expose `onError` prop to catch any error data during creation

### ISSUE THREAD

**Issue by tennisgent** [Cretezy/braintree-web-drop-in-react#242]
We've been using this wrapper for a couple of years now and it's been wonderful. Thank you for creating it. We process hundreds of payments a day using it. It (and the Braintree SDK) seem to work great in almost every instance. Sadly, for whatever reason, we occasionally get random one-off errors from Braintree that happen during the creation phase. Here's an example of one of our Sentry reports where that happened earlier today:

![CleanShot 2020-09-25 at 13 29 53](https://user-images.githubusercontent.com/1782077/94308996-9ddb5200-ff34-11ea-97cb-2c720dc9091b.png)

The error is vague and ambiguous. And we've found that, almost always, if we just try to create the DropIn instance again, it'll work the second time. Given that, we'd like to possibly see if we can improve the user experience for our buyers by auto-retrying if we get such an error. The problem is that we aren't able to catch this error through your wrapper.

Would you be willing to add a prop that would accept an error handler function so that we can catch any errors that Braintree throws and handle them ourselves? Something like:

```js
async componentDidMount() {
  try {
    this.instance = await BraintreeWebDropIn.create({
      container: ReactDOM.findDOMNode(this.wrapper),
      preselectVaultedPaymentMethod: this.props.preselectVaultedPaymentMethod,
      ...this.props.options,
    });

    // existing code for handling extra prop handlers

    if (this.props.onInstance) {
      this.props.onInstance(this.instance);
    }
  } catch (e) {
    if (this.props.onError) {
       this.props.onError(e);
    } else {
       throw e;
    }
  }
}
```

That way we can catch an error if it occurs and choose whether or not we want to attempt to recreate the DropIn instance by simply force-rerendering your wrapper. 

Or if you have other suggestions for how to handle this, we'd much appreciate any suggestions. Thank you again!

**Comment by Cretezy** [comment]
Hi, this is a good catch.

One current alternative that doesn't require any changes are React's Error boundaries. I'll add this though since it's fairly simple.

**Comment by Cretezy** [comment]
v1.2.1 was been published with this feature!

**Comment by tennisgent** [comment]
@Cretezy Thanks! This is exactly what we need. And thanks for the quick response. 👏  🙏
