### ISSUE TITLE
DropinError - There was an error creating Drop-in

### ISSUE THREAD

**Issue by kaloraat** [Cretezy/braintree-web-drop-in-react#29]
The project was working fine a few weeks ago. Today when I try to run again, I keep getting this error:

`DropinError {name: "DropinError", message: "There was an error creating Drop-in.", _braintreeWebError: BraintreeError}`

I am getting the clientToken from backend, no problem there. I even tried using new merchant id , public and private key from Braintree but no success.

Here is my react/App.js code:

```
import React, { Component } from 'react';
import './App.css';
import 'braintree-web';
import axios from 'axios';
import DropIn from 'braintree-web-drop-in-react';

class App extends Component {
  instance;

  state = {
    clientToken: null
  };

  async componentDidMount() {
    console.log(`${process.env.REACT_APP_TEST}`);
    try {
      // Get a client token for authorization from your server
      const response = await axios.get('http://localhost:5000/api/braintree/v1/getToken');
      const clientToken = response.data.clientToken;

      this.setState({ clientToken });
    } catch (err) {
      console.error(err);
    }
  }

  async buy() {
    try {
      // Send the nonce to your server
      const { nonce } = await this.instance.requestPaymentMethod();
      const response = await axios.post('http://localhost:5000/api/braintree/v1/sandbox', {
        paymentMethodNonce: nonce
      });
      console.log(response);
    } catch (err) {
      console.error(err);
    }
  }

  render() {
    if (!this.state.clientToken) {
      return (
        <div>
          <h1>Loading...</h1>
        </div>
      );
    } else {
      return (
        <div>
          <DropIn
            options={{
              authorization: this.state.clientToken,
              paypal: {
                flow: 'vault'
              }
            }}
            onInstance={instance => (this.instance = instance)}
          />
          <button onClick={this.buy.bind(this)}>Buy</button>
        </div>
      );
    }
  }
}

export default App;
```

Any help would be appreciated. Thanks in advance.

**Comment by Cretezy** [comment]
Can you print the `_braintreeWebError` value? That is the actual error from Braintree that will tell you why it's not working. This definitely seems like a Braintree error

**Comment by kaloraat** [comment]
I get the following error message:
```
DropinError {name: "DropinError", message: "There was an error creating Drop-in.", _braintreeWebError: BraintreeError}
message: "There was an error creating Drop-in."
name: "DropinError"
_braintreeWebError: BraintreeError
code: "CLIENT_MISSING_GATEWAY_CONFIGURATION"
details: undefined
message: "Missing gatewayConfiguration."
name: "BraintreeError"
type: "INTERNAL"
__proto__: Error
constructor: ƒ BraintreeError(options)
__proto__: Object
__proto__: Error
constructor: ƒ DropinError(err)
__proto__: Object
```

**Comment by kaloraat** [comment]
<img width="1046" alt="Screen Shot 2019-06-10 at 8 59 17 AM" src="https://user-images.githubusercontent.com/15702617/59165399-75bcb980-8b5e-11e9-848e-f76f7c7ccf4b.png">

**Comment by kaloraat** [comment]
I get the following error message:

```
DropinError {name: "DropinError", message: "There was an error creating Drop-in.", _braintreeWebError: BraintreeError}
message: "There was an error creating Drop-in."
name: "DropinError"
_braintreeWebError: BraintreeError
code: "CLIENT_MISSING_GATEWAY_CONFIGURATION"
details: undefined
message: "Missing gatewayConfiguration."
name: "BraintreeError"
type: "INTERNAL"
__proto__: Error
constructor: ƒ BraintreeError(options)
__proto__: Object
__proto__: Error
constructor: ƒ DropinError(err)
__proto__: Object

```

**Comment by Cretezy** [comment]
As the error states, there's a missing gateway configuration. Could this be that you did not configure any payment methods on the Braintree dashboard? (I've never seen this error but it seems like you forgot to configure something based on the error)

**Comment by kaloraat** [comment]
Isn't this your package?
`import DropIn from 'braintree-web-drop-in-react';`

So once component gets the clientToken from backend, I should be able to see the drop-in ui right?
At the moment I can't see nothing. I have merchant id , public and private key from Braintree all setup correctly otherwise I could not make request from backend to return the clientToken to react.

This is my backend code:

```
const braintree = require("braintree");
require("dotenv").config();

var gateway = braintree.connect({
    environment: braintree.Environment.Sandbox,
    // Use your own credentials from the sandbox Control Panel here
    merchantId: "yxvdkpjnqpq46zg8",
    publicKey: "w973y786ynfh97sd",
    privateKey: "6d793fedf26dce0b1dbeeb05b6e612db"
});

module.exports = function(app) {
    app.get("/braintree", function(req, res) {
        res.send("Braintree route is healthy");
    });

    app.get("/api/braintree/v1/getToken", async function(req, res) {
        try {
            gateway.clientToken.generate({}, function(err, response) {
                if (err) {
                    res.status(500).send(err);
                } else {
                    res.send(response);
                }
            });
        } catch (err) {
            res.status(500).send(err);
        }
    });

    app.post("/api/braintree/v1/sandbox", async function(req, res) {
        try {
            // Use the payment method nonce here
            var nonceFromTheClient = req.body.paymentMethodNonce;
            // charge
            var newTransaction = gateway.transaction.sale(
                {
                    amount: "1.00",
                    paymentMethodNonce: nonceFromTheClient,
                    options: {
                        // This option requests the funds from the transaction once it has been
                        // authorized successfully
                        submitForSettlement: true
                    }
                },
                function(error, result) {
                    if (result) {
                        res.send(result);
                    } else {
                        res.status(500).send(error);
                    }
                }
            );
        } catch (err) {
            // Deal with an error
            console.log(err);
            res.send(err);
        }
    });
};
```

**Comment by Cretezy** [comment]
You accidentally posted you private key in their, I removed your comment and am reposting without keys:

> 
> Isn't this your package?
> `import DropIn from 'braintree-web-drop-in-react';`
> 
> So once component gets the clientToken from backend, I should be able to see the drop-in ui right?
> At the moment I can't see nothing. I have merchant id , public and private key from Braintree all setup correctly otherwise I could not make request from backend to return the clientToken to react.
> 
> This is my backend code:
> 
> ```
> const braintree = require("braintree");
> require("dotenv").config();
> 
> var gateway = braintree.connect({
>     environment: braintree.Environment.Sandbox,
>     // Use your own credentials from the sandbox Control Panel here
>     merchantId: "REDACTED",
>     publicKey: "REDACTED",
>     privateKey: "REDACTED"
> });
> 
> module.exports = function(app) {
>     app.get("/braintree", function(req, res) {
>         res.send("Braintree route is healthy");
>     });
> 
>     app.get("/api/braintree/v1/getToken", async function(req, res) {
>         try {
>             gateway.clientToken.generate({}, function(err, response) {
>                 if (err) {
>                     res.status(500).send(err);
>                 } else {
>                     res.send(response);
>                 }
>             });
>         } catch (err) {
>             res.status(500).send(err);
>         }
>     });
> 
>     app.post("/api/braintree/v1/sandbox", async function(req, res) {
>         try {
>             // Use the payment method nonce here
>             var nonceFromTheClient = req.body.paymentMethodNonce;
>             // charge
>             var newTransaction = gateway.transaction.sale(
>                 {
>                     amount: "1.00",
>                     paymentMethodNonce: nonceFromTheClient,
>                     options: {
>                         // This option requests the funds from the transaction once it has been
>                         // authorized successfully
>                         submitForSettlement: true
>                     }
>                 },
>                 function(error, result) {
>                     if (result) {
>                         res.send(result);
>                     } else {
>                         res.status(500).send(error);
>                     }
>                 }
>             );
>         } catch (err) {
>             // Deal with an error
>             console.log(err);
>             res.send(err);
>         }
>     });
> };
> ```


Your code looks fine. This is my package, however this is a light wrapper over `braintree-web-drop-in`, so the underlying code is straight from Braintree.

In the Braintree dashboard, have you configured any payment methods? I believe this might be the error. Also, can you check that you are passing the `authorization` token in and it is not null?

**Comment by kaloraat** [comment]
It was an issue with my browser. When I opened it in private mode, it worked. @Cretezy  Thanks for your response!
