### ISSUE TITLE
Cannot read property 'requestPaymentMethod' of type undefined.

### ISSUE THREAD

**Issue by celestialorb** [Cretezy/braintree-web-drop-in-react#4]
I copied to code of the complete example and found that it fails on this line:

```
const { nonce } = await this.instance.requestPaymentMethod();
```
with an error of `Cannot read property 'requestPaymentMethod' of type undefined.`
Does this need to be defined in the example, or is something wrong with the current package?

**Comment by Cretezy** [comment]
Are you correctly setting the ref? And are you calling the function after the component has render ed once?
