### ISSUE TITLE
Drop-In Loaded Event

### ISSUE THREAD

**Issue by nysky1** [Cretezy/braintree-web-drop-in-react#41]
Thanks for this wrapper, super helpful! 

I'm noticing that sometimes the dropin version doesn't load timely.  It seems to mostly happen upon file save when the hot update reloads the page.  But it's intermittent.  I don't think it's a connection issue.  

Anyway, is there an event which you can listen for which will tell us the drop-in is loaded?  Or conversely, when the drop-in doesn't load, and we can prompt the user to (potentially) reload.

**Comment by Cretezy** [comment]
I checked the upstream (https://github.com/braintree/braintree-web-drop-in) and it doesn't seem to be possible. Technically, the `onInstance` is only called after the `BraintreeWebDropIn` has been created, which I think is the most in this regard I can provide.

**Comment by nysky1** [comment]
Thanks! I'm thinking of just doing a conditional as well JIC.  But based on your comment, this block below should never run.

{this.state.clientToken === '' ? <div>Loading... If this takes more than a few seconds, click <Link>here</Link> to refresh</div> : <BraintreeDropIn>etc...</BraintreeDropIn>}
