### ISSUE TITLE
Declines

### ISSUE THREAD

**Issue by nysky1** [Cretezy/braintree-web-drop-in-react#42]
I'm not a react pro (yet) and I'm having trouble deciding how to handle declines. I'm using redux and processing the transaction in node and returning relevant info via fetch.  I'm leaning towards just having two different components - one for success and one for failure.  That way, on the failure, I can just navigate back to /payment and the componentDidMount event will run again.  Is that your approach?

**Comment by Cretezy** [comment]
Hi sorry I didn't see this issue before. This wouldn't be on this libraries' side I believe, and would be on `braintree-web`'s side (the underlying library). Please see their documentation on how to see handle this (I don't know how to help you more, sorry!)
