### ISSUE TITLE
How to show Paypal payment method?

### ISSUE THREAD

**Issue by khuong291** [Cretezy/braintree-web-drop-in-react#5]
<img width="772" alt="screen shot 2018-03-23 at 10 14 07 pm" src="https://user-images.githubusercontent.com/11523438/37895759-77bc55ea-310c-11e8-95a7-6825e4059d08.png">

**Comment by Cretezy** [comment]
Check out the Braintree Drop-In docs! This component is simply a React component over it, you'll find the answers there.

**Comment by khuong291** [comment]
Thanks.
