### ISSUE TITLE
How can I set it to show both Paypal and credit card payment method?

### ISSUE THREAD

**Issue by Jim2014** [Cretezy/braintree-web-drop-in-react#6]
The default payment method is credit card, how to display Paypal? thanks.

**Comment by Cretezy** [comment]
See [Drop-In options](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create).

Use the `paypal` option from there. Any documentation/options from Drop-In will be the same for this,
