### ISSUE TITLE
Feature Request: Include 3d-Secure Version 2 integration

### ISSUE THREAD

**Issue by jamesattard** [Cretezy/braintree-web-drop-in-react#60]
At the moment, as per [https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3](https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3), there are a number of fields that are required to integrate with version 2 of 3d Secure.

The current version only supports the `amount `field, as per [https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~threeDSecureOptions](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~threeDSecureOptions).

**Comment by Cretezy** [comment]
This should already be possible. It's using the latest version of braintree-web so it's included in.

You could do something like this:

```js
const threeDSecure = braintree.threeDSecure.create({
  version: 2, // Will use 3DS 2 whenever possible
  client: instance
});

// From example:
threeDSecure.verifyCard({
  amount: '500.00',
  nonce: NONCE_FROM_INTEGRATION, // Example: hostedFieldsTokenizationPayload.nonce
  bin: BIN_FROM_INTEGRATION, // Example: hostedFieldsTokenizationPayload.details.bin
  email: 'test@example.com'
  billingAddress: {
    givenName: 'Jill',
    surname: 'Doe',
    phoneNumber: '8101234567',
    streetAddress: '555 Smith St.',
    extendedAddress: '#5', // When available
    locality: 'Oakland',
    region: 'CA',
    postalCode: '12345',
    countryCodeAlpha2: 'US'
  },
  /**
  * @function onLookupComplete
  * Newly required in `verifyCard` options object, will be called after receiving ThreeDSecure
  * response, before completing the flow.
  * @param {object} data - ThreeDSecure data to consume before continuing
  * @param {string} data.paymentMethod.nonce - payment nonce
  * @param {object} data.threeDSecureInfo
  * @param {boolean} data.threeDSecureInfo.liabilityShifted
  * @param {boolean} data.threeDSecureInfo.liabilityShiftPossible
  * @param {function} next - callback to continue flow
  * */
  onLookupComplete: function (data, next) {
    // use `data` here, then call `next()`
    next();
  }
});
```

As a callback for the `onInstance` method.

**Comment by jamesattard** [comment]
Can I append these as option props to the `<Dropin />` component like we do with the rest of the options?

**Comment by Cretezy** [comment]
You could append these inside the callback of `onInstance` (notice the `client: instance`, which is the value of `onInstance`)

**Comment by jamesattard** [comment]
Apologies if I am asking basic questions, but I have trouble importing `braintree.threeDSecure`. My code is like this:

```
import DropIn from "braintree-web-drop-in-react";
import braintree from "braintree-web-drop-in";
...
            <DropIn
              options={{
                authorization: this.props.token, // from redux
                card: { cardholderName: true }
              }}
              onInstance={instance => {
                this.instance = instance;
                this.setState({ renderedDropIn: true });

                // Configure 3D secure
                const threeDSecure = braintree.threeDSecure.create({
                  version: 2, // Will use 3DS 2 whenever possible
                  client: instance
                });

                threeDSecure.verifyCard({
                  amount: "500.00",
                  nonce: this.
...
```

I get the following error in the browser console:

> Unhandled promise rejection TypeError: "braintree_web_drop_in__WEBPACK_IMPORTED_MODULE_12___default.a.threeDSecure is undefined"

**Comment by Cretezy** [comment]
I think this is an upstream issue. Since this is just a wrapper over `braintree-web-drop-in`, you should take it upstream and see what they have to say!
