### ISSUE TITLE
update braintree dependency

### ISSUE THREAD

**Issue by pho3nixf1re** [Cretezy/braintree-web-drop-in-react#7]
Google pay support was [added in 1.10.0](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#1100) and some important fixes were included in [1.11.0](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#1110). I'm not to the point of deploying this yet but will be soon. If this change hasn't been made then I will open a PR in a week or so.

**Comment by Cretezy** [comment]
Updating soon! Do the PR if you wish

**Comment by Cretezy** [comment]
Version v1.0.4 updates to Braintree v1.11.0, https://github.com/Cretezy/braintree-web-drop-in-react/releases/tag/v1.0.4
