### ISSUE TITLE
How to pass the Customer ID to braintree

### ISSUE THREAD

**Issue by luanfonceca** [Cretezy/braintree-web-drop-in-react#8]
Hi folks, i created a Customer on my sandbox account and then copied the `Customer ID` in order to fetch the customers' saved cards. But i'm not seeing on docs how to pass it to the braintree js sdk through `BraintreeDropIn` react component.

Follows my component definition:
```js
<BraintreeDropIn
  braintree={braintree}
  paymentOptionPriority={['card', 'paypal']}
  customerId={this.state.customerId} <--
  card={{
    cardholderName: true
  }}
  paypal={{
    flow: 'vault'
  }}
  authorizationToken={this.state.authorizationToken}
  handlePaymentMethod={this.handlePaymentMethod}
  onCreate={this.onCreate}
  onDestroyStart={this.onDestroyStart}
  onDestroyEnd={this.onDestroyEnd}
  onError={this.onError}
  renderSubmitButton={paymentButtonComponent}
/>
```

Thanks in advance.

**Comment by Cretezy** [comment]
Put your options in the `options` prop as mentioned in the document
